### ISSUE TITLE
Close Other Windows 0.1 with Firefox on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [mystor/close-other-tabs#1]
https://addons.mozilla.org/firefox/addon/close-other-windows/

> Compatible with Firefox 57+ … Works with Firefox for Android 48.0 - *, Firefox 48.0 and later …

I can not install the extension with [Firefox 54.0.1 (64-bit) on FreeBSD](http://www.freshports.org/www/firefox). Is there something in the code that's intended for Linux but not for FreeBSD? 

## Related

[Firefox Sync failing to sync at least eleven exensions - Add-ons / Add-on Support - Mozilla Discourse](https://discourse.mozilla.org/t/firefox-sync-failing-to-sync-at-least-twelve-exensions/17748?u=grahamperrin)

**Comment by mystor** [comment]
There's nothing linux-specific in this addon, and I don't do anything fancy. I don't know anything about how the FreeBSD package maintainers do their build so it might not work if they disable webextensions or similar. I'm not sure.

**Comment by grahamperrin** [comment]
Thanks. As https://github.com/mozilla/addons/issues/468 is closed, so this can be closed.
